Loading python3/3.9.2
  Loading requirement: intel-mkl/2020.3.304
Traceback (most recent call last):
  File "/home/561/jm2369/thesis/stage6/plot_accuracy.py", line 27, in <module>
    train_accuracy = train_accuracy[0]
IndexError: list index out of range
